### ISSUE TITLE
AutoUpdate Fails. Says script has been updated, even on new untouched pull. 

### ISSUE THREAD

**Issue by texastoastt** [mrworf/plexupdate#102]
Receiving the following error, even when trying to perform on a freshly cloned pull from github. 

ERROR: You have made changes to the script, cannot auto update

**Comment by mscreations** [comment]
Any extra info you can provide?

What OS? 
What version of git do you have? (git --version)
If you are in the plexupdate cloned directory, what do you get from running the command "git status"?

**Comment by texastoastt** [comment]
Of course, here's the requested info:

~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

~]# git --version
git version 1.8.3.1

plexupdate]# git status
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   README.md
#	modified:   plexupdate.sh
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	plexmediaserver-1.1.3.2700-6f64a8d.x86_64.rpm.sha
no changes added to commit (use "git add" and/or "git commit -a")

**Comment by mrworf** [comment]
You have made some changes to the file, please do ```git diff``` and publish here. My guess is that git is set to convert line endings.

If you run ```git config core.autocrlf``` and it returns true, then you've found the issue. It should be false.

If you accidentially changed files, please run ```git checkout -- .``` in the folder to reset to normal. Please remember that if you want to override settings, you should place a .plexupdate file in the home folder of the user running the script instead of changing the plexupdate.sh if you want to use the auto update feature.

**Comment by mrworf** [comment]
@texastoastt Any update?

**Comment by mrworf** [comment]
I'm assuming it works now, please reopen if you still have issues
