### ISSUE TITLE
Script doesn't work with PlexPass

### ISSUE THREAD

**Issue by cpecquerie** [mrworf/plexupdate#12]
Thanks for your script, very useful !

Trying to update with my login/pwd in script just downloads plexmediaserver_0.9.12.4.1192-9a47d21_amd64.deb while plexmediaserver_0.9.12.7 is available for plexpass users.

**Comment by xombiemp** [comment]
I saw this happen recently.  It was because the credentials were wrong in the script configuration.  Try to login with those credentials in a browser first to make sure they actually work.

Along the same lines, the script should warn you that the credentials didn't work if they are populated in the script config.

**Comment by mrworf** [comment]
Fixed, now prints out if you have the wrong username/password (that was indeed the issue, I had the same problem :))
