### ISSUE TITLE
New logging functionality seems to break -c output

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#129]
I believe this started with the changes in #120, but the -c log output produced now isn't very useful to me. The only output I'm getting is the systemd output of the service files being replaced. I can find the script output in `/tmp/plexupdate.log` but this, to me, defeats the purpose of -c (which is to get an email with the full output of plexupdate _if changes are made_).

I haven't had time to review the full set of changes involved (or, rather, review them long enough to understand them all), but I expect that this is due to how the new `*Log*` functions handle output vs output being produced to `STDOUT/STDERR` by outside applications. This would explain why the dpkg/systemd output shows up in the cron emails (written straight to `STDOUT/STDERR`) while none of plexupdate's output does (written directly to `FILE_STDOUTLOG`).

/cc @mscreations

**Comment by mscreations** [comment]
I'm not entirely sure what would be different. I tried to mimic the existing behavior plus output to the log no matter what. To that extent, if you specify cron mode, it will still output to the log to stdout (See [line 531](https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L531)) but it also keeps track of all lines actually added to the log (the log is never erased, only appended to). So, there is a variable [OUTPUTLINES](https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L53) that get's incremented anytime you call the Log function (which is what sends info the the log file). Then, if the exit code is not 5 (for already installed) it reenables the stdout and rather than doing a cat on the logfile, it asks for only the lastly added lines (as counted by OUTPUTLINES and output by tail).

I will note that I am using a systemd timer to run plexupdate instead of cron, but maybe cron is handling this differently for some reason.

**Comment by demonbane** [comment]
Finally got a chance to review the code fully here.

The problem is that the logging functions you've added only log output that is explicitly sent to them. Output created by applications called by plexupdate just end up having their output sent to `/dev/null`.

For example:

```bash
if [ "${AUTOINSTALL}" = "yes" ]; then
        if ! hash ldconfig 2>/dev/null && [ "${DISTRO}" = "ubuntu" ]; then
                export PATH=$PATH:/sbin
        fi
        # no elif since DISTRO_INSTALL will produce error output for us

        ${DISTRO_INSTALL} "${DOWNLOADDIR}/${FILENAME}"
fi
```

When `DISTRO_INSTALL` is called, any output it generates ends up going to plain old STDOUT, not to a log file. However, since STDOUT has been redirected:

```bash
if [ "${CRON}" = "yes" -o "${QUIET}" = "yes" ]; then
        # The new logging features automatically redirect to the log no matter what. 
        # Redirect STDOUT to dev null. Use >&3 if you really, really, REALLY need to print to STDOUT
        exec 3>&1 >/dev/null
fi
```

That output now ends up going to `/dev/null` instead, so it ends up lost forever.

Since you added the logging functionality I think it'd be best if you manage any changes for this since you know that code best. I'm happy to do it myself as well, but my PR is likely to start with `git revert d9253e193` which is kind of the definition of "counterproductive". 😅

**Comment by mscreations** [comment]
I see what you mean. Yeah, that is definitely an issue. I mostly have it corrected, but still checking to make sure I didn't miss anything.

**Comment by demonbane** [comment]
I just had an opportunity to test this because there was a new update waiting, but it doesn't appear to have worked. While the log file did seem to get the command output this time, none of that output made it to STDOUT.

**Comment by mscreations** [comment]
I have no clue why it wouldn't make it to stdout. [Line 563](https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh#L563) restores STDOUT right before tail should output the log file.

**Comment by demonbane** [comment]
I had to do a bunch more poking around and here's what I've come up with.

1. Every time the script runs, whether or not it should produce output based on the exit code, I always get one line of output in cron emails saying: `Using configuration: /root/.plexupdate` I think this is likely just a bug in that particular logging function but I haven't tracked it down yet.

2. This change redirects STDOUT and STDERR to different log files, but the output of those files never goes anywhere, hence why it still doesn't fix the problem. This, unfortunately, leads me into a broader issue... 

3. The overall changes implemented to logging disregard the difference between **execution output** and **log output**. These are fundamentally different concepts. A log should log information **in addition to** output, not in place of it. At the time that these changes were submitted, it may have appeared that we were doing "real" logging, but the log file was essentially just being used as a **buffer** for STDOUT and STDERR. (I had actually wanted to use a FIFO for this, but since FIFOs block until a read, the file approach ended up being necessary.)

4. As a result, I'm strongly of the opinion that we should not be implementing a full logging solution inside of what is meant to be a "simple" bash script (at 625 LOC and counting... 🙄), but should allow end users to manage any advanced logging through redirects or wrapper scripts if required. (we could also provide a sample wrapper script that implements the current logging functions)

P.S. Being a bash neckbeard, I also abhor camelCase, but that's just me. :smile:

**Comment by mrworf** [comment]
I agree... It started out with the best intentions and good work by @mscreations but it seems to have taken on a life by itself and become unnecessarily kludgy.

So... I've kinda done some work now to improve the situation, please checkout the new branch "reworklog".

The new solution makes away with both quiet and cron options. quiet can be accomplished with >/dev/null and cron is handled by cronwrapper.

Cronwrapper is needed anyway on an ubuntu system since you cannot simply drop plexupdate.sh into any of the cron.* folders. It also adds logging to facility and washing of return codes. 

This design also leaves room for doing some nicer handling of a busy server by retrying to apply the update if users are online.

Thoughts? It's kinda jarring so I didn't want to drop it on people. Also need to update the wiki with new details on cronwrapper before merging into master.

@mscreations @demonbane let it rip! 😜
