### ISSUE TITLE
Merge conflict for reworklog

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#144]
Looks like the squash commit from #140 really did a number on the history, so trying to merge reworklog back into master now causes a huge conflict. Trying to figure out a fix now.

**Comment by demonbane** [comment]
The easiest option I can find at the moment is to just create new PR from demonbane/master to mrworf/master. I'll do a merge --squash from demonbane/reworklog to demonbane/master so it'll look identical to the current state, and then send a PR for that merge instead.

I'm running late for an appointment right now, but I'll open the new PR as soon as I get back to my computer.

**Comment by demonbane** [comment]
I opened #145 to address this.

**Comment by mrworf** [comment]
How did you do the merge? Because I had no issues at all. This is what I did:

```
git checkout master
git pull
git checkout reworklog
git pull
git rebase master
```
at this point, I got a conflict due to same fix on both branches but done using different commits
```
git checkout --theirs plexupdate.sh
git add plexupdate.sh
git rebase --continue
```
and that was all the issues I saw
```
git checkout master
git merge reworklog
git push
````
Anyway, hope you don't mind me skipping the PR. But I appreciate the work in testing out the changes. And just to be safe, I did do a ```diff -r``` between my master and yours and no diff was found.

**Comment by demonbane** [comment]
It looks like whatever you did fixed it. I just tried it now and it worked with no problem. I tried it 3 times this morning with a clean clone each time and got merge conflicts every time (and with pretty old code changes at that).

But I think we're all set now. Closing this out.
