### ISSUE TITLE
Notify on update

### ISSUE THREAD

**Issue by demonbane** [mrworf/plexupdate#150]
I just realized that with the changes in 440de0c, we no longer provide any feedback on cron runs if an update exists, which makes cronwrapper largely useless for anyone not using AUTOINSTALL.

Since @mrworf just went through the effort of removing an exit code, I wanted to open the implementation up for discussion before submitting a PR. The options are:

1. Have plexupdate return a non-zero exit code if an update is available or if an update is installed.

2. Have cronwrapper scrape the output of plexupdate looking for an indication that an update is available.

I think option 1 is obviously the better choice, but I just wanted to get some consensus before moving forward.

**Comment by mrworf** [comment]
Hmm.. but wouldn't it download the new version if found? So wouldn't it mean that we could just look for a new file in the filesystem afterwards instead? I don't believe there is a mode to only find new version?

In other words, ls -la output directory, run plexupdate, ls -la output  and diff it, if different and contains plexmediaserver, then new update downloaded. This would also stop it from continuously spam you with emails every time it checked for updates. Also makes us oblivious to scraping.

**Comment by demonbane** [comment]
It **might** download the new version, but if it was downloaded previously and couldn't update due to the server being in use, the next time it updates we won't know about it. Either way, it's not a big departure from scraping the output because we're trying to ascertain status indirectly, which is a bug just waiting to happen.

If you want to stay away from bringing exit code 5 back for a different purpose, we could easily use 6 for all 3 cases: "update was attempted". An email will get sent out with any output, so the user will be able to see if there was an update available and whether or not it got installed from the output.

We can also look at retiring some of the other exit codes that don't have a clear programmatic purpose. 2 doesn't provide anything useful AFAICT, 3 is only useful for troubleshooting errors which we'll be doing anyway, and 4 can probably be consolidated into 1 since it's still an error.

So we could do with just:

0. Everything is fine, no update
1. An error occurred, check the output
2. An update is available (and may have been installed, check the output)

**Comment by demonbane** [comment]
When I started looking at the code I realized that returning non-zero in the case of an update was literally as simple as changing the exit line at the end of plexupdate since that's the only way that it would be reached. So I went ahead and just threw together a PR to implement that, as well as an optional commit to simplify exit statuses if you'd like to go with the suggestion above as well.

**Comment by mrworf** [comment]
I'm really not fond of having a non-zero exit code on success. This would get us right back into the debacle we had before which caused the massive rewrite of 2016 😉 

I'd rather implement it as a different mode, "check for update" which returns 0 if found or 2 if not found. This option would be mutually exclusive with autoinstall and will cause 255 if you combine the two. This way, the app would behave as you'd expect and only produce an error exit code if no update is available (kinda like grep does, 0 on found, 1 if not).

**Comment by demonbane** [comment]
Why even make it mutually exclusive with autoinstall? If there are no updates, we return 2, and if there are updates we return 0. If auto install succeeds, we return 0, and if auto install fails we return whatever `DISTRO_INSTALL` returned. Then cronwrapper can just monitor for `[ $RET -ne 2 ]` and we're good.

**Comment by mrworf** [comment]
The use-case is to not auto install but still be told about if there is a new version or not. With auto install you'll never get any info (really) since if there is no updates, I don't want to be told, if there is an update it will be installed and no message then either. We'd only get a message whenever there is no new version or a failure of some sort.

Also, your suggested logic won't be that easy either, since we only want cron to report when there is a new version, and not any other time. This forces us to make cronwrapper aware of the desired mode of plexupdate. Unless we intend to have two different wrappers for different purposes (yuck). And yes, we could change so exit code is 2 when version is downloaded and zero if not in this mode, but it makes it go against all existing command line tools in that it doesn't return success when it actually succeeded.

To be honest, the easiest way to support your request, is actually to scrape the log output (which we have anyway). You end up with these three lines in cronwrapper:

```
if  ${NOTIFYDOWNLOAD:-false} && grep -q "File downloaded" ${LOGFILE} ; then
     RET=1
fi
```

Allowing you to simply say `NOTIFYDOWNLOAD=true` and you'll get a email from cron whenever it successfully downloads the file. 

I feel this is much simpler to do than us rewriting parts of cronwrapper and plexupdate.sh to be command line nice and all just to get a notification.

Yes, it's scraping, but we control the entire flow 😄

**Comment by demonbane** [comment]
> Also, your suggested logic won't be that easy either, since we only want cron to report when there is a new version, and not any other time.

That's not entirely correct. I'd say we want cronwrapper to report if there is a new version, OR if an action has been taken (such as AUTOINSTALL), OR if there's an error.

Or, to put it more succinctly, the only time we **don't** want to notify the user is if there is no update. In pretty much every other case, we do.

**Comment by mrworf** [comment]
In that case, we need to change things up a bit anyway since we're not doing that today.

**Comment by demonbane** [comment]
That is what we were doing prior to 440de0c.

**Comment by mrworf** [comment]
Yes, we were sending emails on a daily basis, even if nothing changed at all which was less than stellar 😄. To send emails when there is something of value, we can do it two ways:

1. Add plexupdate.conf option to turn the last `exit 0` into `exit 2` (ie, reimplementing a version of CRON=yes)
2. Do a three-liner which scrapes the output

Obviously, #1 is better, but it has to be protected with an option to enable this, since it might not be what people want, not to mention, success would now be an error code instead of zero. 

The installer can ask about this with the default being Yes, send me updates.

At this point, we've now reimplemented cron mode `-C` 😜

**Comment by demonbane** [comment]
I think one of us is confused, and I'm not sure who it is. 😄

Prior to 440de0c, we would only send an email if a new version was available, a new version was installed, or an error occurred. So the only way you'd be getting an email every day is if you had `AUTOINSTALL=no`, a new version **was** available, **and** you still hadn't installed it. But that's exactly what would happen right now anyway.

If this is **not** what was happening then I would consider that a bug. (but I'm pretty sure that's what **was** happening since I'd spent weeks testing that branch before we merged it :) )

**Comment by mrworf** [comment]
That would be me 😸 I misremembered and mixed it with your proposed patch. 

But if we combine my somewhat incorrect comment with your current proposal, we would get the behavior I described, no?

**Comment by demonbane** [comment]
So just we're on the same page before I update the PR, here's my most recent proposal (based on your proposal to make 0 the default if updates are available):

* If no update is available, exit with 2
* If an update is available, or an update has been installed, exit with 0

In terms of emails from cronwrapper, an email will be sent out if:

* an update has been found/downloaded/installed
* an error occurred

Does that all sound right to you? The only other detail then is whether or not you want to also simplify the exit codes to just 0-2, or if you want to keep the existing 0-6 in place.

**Comment by mrworf** [comment]
I think we can simplify the codes, the text will give everyone enough info anyway.

As for error code 2 ... I know that's going to give some complaints from people doing their own solution for automatic updates (including systemd) and it doesn't really make sense to error on that fact that you have the latest version installed. For example, `apt-get install wget` will not give you an error code for already having it installed. 

I don't know if you had a chance to look at my comments on your PR I did earlier. It introduced a new option to make `plexupdate.sh` produce a exit code of 2 if any update is available/downloaded/installed (if I remember correctly), preserving existing behavior by default and supporting this if using cronwrapper.

Sorry for bouncing back again, just want to make sure we don't frustrate too many people with this change 😄 

But I agree with email sent out if:

- an update has been found/downloaded/installed
- an error occurred

Man, we could use a chat instead of going back-n-forth :)

**Comment by sufr3ak** [comment]
I know it's been a while since this has been discussed. And to be honest, I have stepped away for a bit since Plex DVR was beta only. But now it's merged with the Plex Pass channel. Boy, I got some catching up to do.

I wanted to echo support for this. I run "status" scripts on my stuff and I am trying to integrate a way to report the current version, as well as the current available version. I don't specifically want to install.  I prefer to do that under my own control, since I'm testing out beta features. 

So...it would be a nice feature to have a CLI to report back either current or available versions. For now, I'll just parse the JSOn they report. Thank goodness for jq.

**Comment by cyberbrix** [comment]
echoing the previous poster - (along the lines of my other issue I opened)... it would be trivial to script this, using, as they said, jq.

curl -s 'https://plex.tv/api/downloads/1.json?channel=plexpass&X-Plex-Token=<PlexToken>' | jq '.computer[] | select(.id == "linux") | .version' | sed 's/-.*"//g;s/"//g'`

will give you the current linux version. you can even expand it to get the download url.
