### ISSUE TITLE
No Python

### ISSUE THREAD

**Issue by justinglock40** [mrworf/plexupdate#163]
[root@HDA jwashington]# /root/plexupdate/plexupdate.sh --config="/root/plexupdate/.plexupdate"
Authenticating with plex.tv
Retrieving list of available distributions
Downloading release "plexmediaserver-1.4.1.3362-77c6a4f80.x86_64.rpm"
/home/jwashington/p 100%[===================>]  97.88M  2.69MB/s    in 28s     
File downloaded
Last metadata expiration check: 2:54:45 ago on Tue Feb 14 18:04:41 2017.
**Error: nothing provides /usr/local/bin/python needed by plexmediaserver-1.4.1.3362-77c6a4f80.x86_64**
(try to add '--allowerasing' to command line to replace conflicting packages)
Deleted "plexmediaserver-1.4.1.3362-77c6a4f80.x86_64.rpm"

**Comment by demonbane** [comment]
Was Plex working properly before you tried updating, or were you using plexupdate to install Plex for the first time on this machine?

Did you use the installer.sh script to set up plexupdate?

And which Linux distribution and version are you using? (Red Hat, Fedora, CentOS, etc.)

**Comment by demonbane** [comment]
Looks like this is an upstream problem: http://forums.plex.tv/discussion/258388/pms-linux-redhat-1-4-1-package-installation-failure

The Plex team is going to be putting out an updated version soon. If you haven't rebooted your system since you tried the update, and if you haven't manually set the download directory to something custom, the following command should fix it for now:

`sudo rpm -Uvh /tmp/plexmediaserver-1.4.1.3362-77c6a4f80.x86_64.rpm --nodeps`

Otherwise you can just manually download this release and insert the full path to the rpm in this command.

**Comment by mrworf** [comment]
Added a commit to try and catch when install fails and provide a helpful indication that it's not a plexupdate problem :)

**Comment by mrworf** [comment]
Closing this issue since it's related to plex and not this script.
