### ISSUE TITLE
Setting the Cron Notification Email Address?

### ISSUE THREAD

**Issue by zanechua** [mrworf/plexupdate#183]
I looked through the script and I am assuming that the notification email address is the email address associated with the Token?

Probably should mention somewhere that you can override this email address?

**Comment by kingsleyadam** [comment]
I assume it's the email associated with the account running the cron job.

I set an alias on my root to have all emails forward to my personal email. The emails that come through for all sudo cron jobs including this one is to root@localhost.

**Comment by zanechua** [comment]
ah. right. I wasn't sure if it was the plexpass email address or the actual ubuntu user email address.

I just took a short look and a guess

**Comment by mrworf** [comment]
That's a valid point, should update the README to point that out. Thanks!

**Comment by brimur** [comment]
Hi guys, so which one is it? I did not receive a notification email to my plexpass gmail email and there was also "no mail for root" on the Plex server. I just want to see when there was an actual update/install so if that is saved to a log somewhere that would be good enough. Something like <date> <version installed>? The cron entries in syslog dont tell me anything usefully

**Comment by kingsleyadam** [comment]
@brimur, it's the email settings you have setup on the server but whichever account is running the cron job. I assume that's the root account.

You'll need an email package installed, I use PostFix. And depending on if your ISP allows it you may also need to setup a relay server in PostFix. That's what I had to do as my ISP blocks emails being sent.

The email comes from the cron daemon and shows the entire installation log from downloading to processing triggers.

I haven't ever actually checked the logs because my email is working but you can look for the string 'Setting up plexmediaserver' and about 10 lines before and after.

**Comment by mrworf** [comment]
@kingsleyadam is correct, on ubuntu I tend to use nullmailer and then in the crontab I have MAILTO set to the user I want the email to go to.

Just add `MAILTO=john.doe@void.com` as the first line and that will be the user who gets the email (obviously substitute with correct address :) )

Closing this issue since it's a configuration of Linux issue more than a plexupdate problem
