### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by jbbenac** [mrworf/plexupdate#184]
Hello,

While using the installer, at the end of the process, I get :
./extras/installer.sh: ligne 356: -E : commande introuvable 
(command not found)

What can I do ?
Thanks in advance :)
Best,
JB

**Comment by demonbane** [comment]
Which distro and version of sudo are you using? That error is about the '-E' option to sudo which, as far as I can find, has been in sudo since at least 2007 and probably earlier.

That error doesn't happen in a critical part of the code, I'm just concerned that if your copy of "sudo" is really out of date there may be other components that could cause problems later as well.

**Comment by demonbane** [comment]
@jbbenac Are you still having this problem?

**Comment by mrworf** [comment]
Closing this issue. Please re-open if still relevant, but in order to help we'll need more info :-)
