### ISSUE TITLE
Feature Request Non Interactive install script

### ISSUE THREAD

**Issue by shadycuz** [mrworf/plexupdate#189]
It would be nice if your choices were stored in the config file, that way I can copy the config file to a new server and run the install script without interacting with it.

**Comment by demonbane** [comment]
Since almost all of the questions map directly to actual options, most of them already are stored in the config file. Adding a non-interactive option to the installer would be pretty easy, I'll just have to double-check which options don't get saved in a way that is guaranteed to be accurate (i.e. if an option isn't set, is it because you answered no or because you didn't run the installer and just haven't defined it?).

I'll try to take a look at it this weekend and see if it can be added without over-complicating the existing code.

**Comment by shadycuz** [comment]
Well I'm very grateful. I'm going to use this in an ansible script and I like to use plexupdate to install plex from scratch. 

Thanks,
Levi
