### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tazboyz16** [mrworf/plexupdate#195]
I don't know what changes have happened since February but I have been using your script as a standalone updater/installer for my scripting,  now it requires to have multiple files just to run for non plex pass. Im inquiring if possible to have a standalone script be created again?

Thanks

**Comment by tazboyz16** [comment]
The issue I get is with line 99  when running script with -p -a -d

**Comment by demonbane** [comment]
The error that you're getting is because it can't find plexupdate-core, which is required. The preferred fix is to either [run the installer](https://github.com/mrworf/plexupdate#installation) or [install using git](https://github.com/mrworf/plexupdate/wiki/Manually-installing-plexupdate#using-git-to-clone-recommended), but if you **really, really, really** don't want to either, the easiest thing is just to download plexupdate.sh and plexupdate-core. As long as you have those two in the same directory everything should work as normal.

**Comment by tazboyz16** [comment]
ok either option is not going work with my automated Media Server Installer. i do thank you for the quick reply thou

**Comment by tazboyz16** [comment]
Found another fix for me. Replaced the If statement for the plexupdate-core with its contents
