### ISSUE TITLE
Question about email/pass breaks scripts

### ISSUE THREAD

**Issue by cfsmp3** [mrworf/plexupdate#200]
Assuming that if the script is run on a terminal it implies there's a human there to answer question is quite a long stretch... for me it's run as part of a very long process. Yes, there's typically a terminal, but definitely not a human around, so interrupting the process is definitely a no go.

Can we have a parameter to guarantee that no question will be asked ever? Really breaks unattended processes that count on all the called scripts to just do their work. 

Failing is OK, but stopping...

**Comment by demonbane** [comment]
The only time that prompt should ever come up is when we're looking for your Plex token. And then, it only comes up if every other way of getting the token has failed. You can always disable the prompt by just passing in some dummy input (i.e. `./plexupdate.sh <<< "foo"`), but I'd suggest looking at why the token is needed and why it's failing to find it.

If the server you're running the script on is the same one that Plex is installed on, it means that it can't find the Plex Media Server directory to get the token directly from it. That can be fixed by, for example, making sure that `PLEX_MEDIA_SERVER_DIR` is set in `/etc/defaults/plexmediaserver`. (Even if you're using systemd and not sourcing that file, plexupdate will still check it for settings if it exists.)

The other option is to just hard-code the token into your configuration, or pass it in as a parameter. You can pass it in at runtime with `--token`, or just add `TOKEN=<yourtoken>` into your `/etc/plexupdate.conf`.

Finally, if you don't know how to get your token, there's a fix for that too. Just run the following in your plexupdate directory:

```bash
bash -c 'source plexupdate-core' get-plex-token
```

**Comment by cfsmp3** [comment]
I have a premade Virtualbox image with (an stale version of) Plex. If the
token is something that is generated the first time I log in into Plex,
then it's just not there at all when plexupdate is run the first time. At
some point the virtualbox instance created from that image is actually
started, the user log ins (if he uses Plex at all, which may or may not
happen), and (I assume) that's when the token would be generated.

So I'd need a way to just exit on the condition "no token yet".

**Comment by cfsmp3** [comment]
I have a premade Virtualbox image with (an stale version of) Plex. If the token is something that is generated the first time I log in into Plex, then it's just not there at all when plexupdate is run the first time. At some point the virtualbox instance created from that image is actually started, the user log ins (if he uses Plex at all, which may or may not happen), and (I assume) that's when the token would be generated. 

So I'd need a way to just exit on the condition "no token yet".

**Comment by cfsmp3** [comment]
I have a premade Virtualbox image with (an stale version of) Plex. If the token is something that is generated the first time I log in into Plex, then it's just not there at all when plexupdate is run the first time. At some point the virtualbox instance created from that image is actually started, the user log ins (if he uses Plex at all, which may or may not happen), and (I assume) that's when the token would be generated. 

So I'd need a way to just exit on the condition "no token yet".

**Comment by demonbane** [comment]
Yeah, the token doesn't get generated until the server is "claimed" through Plex. So the reason we're asking for username/password is because you're doing something that requires it. Most likely trying to update with a PlexPass version. If you want to update to a PlexPass version, you **must** provide a token. However, if you're ok with just updating to the latest public release, you can either add `PUBLIC=yes` to plexupdate.conf or just run plexupdate with `-p` and you should never get prompted for email and password.

If the users that claim the instances may want to use PlexPass updates, I'd recommend leaving `PUBLIC=no` in the config file, and just running plexupdate with `-p` the first time. That way, once they claim the server, it'll automatically revert to doing PlexPass updates if possible.

**Comment by mrworf** [comment]
@cfsmp3 This might have been fixed by 193f8f8 since we now handle unclaimed servers (as long as you don't need PlexPass version of Plex). Please test and let us know.

**Comment by mrworf** [comment]
@cfsmp3 Any update?

**Comment by cfsmp3** [comment]
Seems to be working correctly, thanks.
