### ISSUE TITLE
Plex should be shut down properly before update

### ISSUE THREAD

**Issue by Reed97123** [mrworf/plexupdate#215]
I was browsing the code, beautiful job, by the way, and noticed something.

For Ubuntu:
While you restart Plex after installation with "systemctl start plexmediaserver" you don't stop it properly before the install with "systemctl stop plexmediaserver".

I'm not exactly sure what happens when dpkg installs over a currently running program, but it seems like any ambiguity about whether it might be an issue could be avoiding by stopping it properly.  I'm mostly concerned with database corruption that might occur.

[Asked about this on Plex's forums](https://forums.plex.tv/discussion/comment/1559416#Comment_1559416)

**Comment by demonbane** [comment]
The answer from ChuckPA on the forums is **partially** right, but not exactly. The full answer is, it depends. The tl;dr version is that all modern package managers (including yum and dpkg) are smart enough to safely do whatever they need to do with a program before upgrading it in place, so this isn't necessary. But if you'd like to know how, grab a drink and relax because this'll take a while. :)

## deb package update process
To find out exactly what happens during an upgrade, you can open up the `plexmediaserver_<version>.deb` file and look at the control files by running `dpkg -e <deb file> <dir to extract to>`. Inside, you'll find 4 scripts that are executed in the following order during the upgrade:

1. `prerm`
2. `preinst`
3. `postrm`
4. `postinst`

If you want to know exactly what each of them is and exactly when they run, you can read up on [maintainer scripts](https://wiki.debian.org/MaintainerScripts).

In our case, w're interested in 2 of them in particular.

### `prerm`
This is the first script that gets run as soon as you start upgrading a package using dpkg/apt. It does basic cleanup in preparation for installing the new version.

In it, you'll find code that checks to see if you're running systemd. systemd has been the default on Ubuntu systems since 15.04, so assuming you've updated your system in the last 2.5 years, you're running systemd.

If the script finds that you are running systemd, it runs:
```
systemctl stop plexmediaserver.service
systemctl disable plexmediaserver.service
```
So before anything else is done, plexmediaserver has already been stopped, and systemd has been told not to start it even if something else asks it to.

### `postinst`
After all the files from the new package have been moved to the right place, the final script that gets run is `postinst`. If you look at this script, you'll find a very similar section that also checks for systemd. In this section you'll find:
```
systemctl enable plexmediaserver.service
systemctl start plexmediaserver.service
```
This re-enables plexmediaserver, and then starts it. Hence why you don't need to worry about `plexupdate` stopping and starting the services for you.

## Note
`plexupdate` will only start plexmediaserver after installation if you specifically tell it to with the `AUTOSTART` option, but as we mention in the docs, this is only really necessary on RedHat-style systems. Ubuntu and Debian don't need this option since the package itself will take care of that for you.

If you go ahead and specify it anyway it won't hurt anything since systemd is smart enough to check if a service is already running before trying to start it again.

**Comment by Reed97123** [comment]
Fantastic, thanks for clarifying the subject!
