### ISSUE TITLE
plexmediaserver status: unrecognized status

### ISSUE THREAD

**Issue by ematogra** [mrworf/plexupdate#219]
Fairly new to Linux, running Debian 7.11

After running plexupdate with plex pass, it seems to install the latest Plex version fine.. but when I run

```
service plexmediaserver status
```

I get

```
plexmediaserver: unrecognized service
```

I've tried restarting but it makes no difference.

Any help would be much appreciated. Thanks!

**Comment by demonbane** [comment]
I had to do a bit of checking first, but it looks like the short answer is your Debian install is just a bit too old. I just checked the most recent packages for PMS, and they no longer include sysvinit startup files which is what Debian Wheezy still uses. They now only ship upstart and systemd.

If you can't/won't upgrade to a newer release of Debian, you may be able to just [install systemd on Wheezy](https://scottlinux.com/2014/10/20/how-to-switch-to-systemd-on-debian-wheezy/), but your best bet is to just upgrade to either [Jessie (8.10)](https://www.debian.org/releases/jessie/) or [Stretch (9.3)](https://www.debian.org/releases/stretch/).

**Comment by ematogra** [comment]
Seems to have worked. Updated to Jessie. Thanks a lot for the help.

Should I just leave it on Jessie for now is it a good idea to update to Stretch soon as well?

**Comment by demonbane** [comment]
Since you're already updating, I'd definitely at least go to Stretch. If you're using this as a media PC, however, I'd suggest going all the way to "testing" (currently this is "Buster") and sticking with "testing" going forward. (Since Debian does rolling releases, Buster will eventually become "stable", and the new "testing" will be Bullseye and so on. See [Debian Releases](https://wiki.debian.org/DebianReleases#Production_Releases) for details.)

If you're really adventurous you can try going all the way to "unstable" which is a bit of a [misleading name](https://raphaelhertzog.com/2010/12/20/5-reasons-why-debian-unstable-does-not-deserve-its-name/). (I've been running Debian "unstable" on my home systems for about 20 years with very few problems along the way.)

**Comment by ematogra** [comment]
Thanks, will do that!

I've just updated to Stretch but I seem to have lost the connection to my media raid. It's mounted because I can access my media through Plex, but when I try connect via samba it only shows my username (containing documents, downloads, etc. on my root drive)

**Comment by ematogra** [comment]
Managed to fix it- my smb.conf had been reset, so I just added the share back into there. Thanks!
