### ISSUE TITLE
Maintain 'x' downloaded files after each run

### ISSUE THREAD

**Issue by adhawkins** [mrworf/plexupdate#220]
Hi,

I think it would be useful to extend the 'delete after install' option, to have it keep a 'history' of the last 'x' downloads. That way if it downloads a version with an issue, you still have the previous files available to revert back to a previous version.

This is relatively simply achieved in script. e.g.

`ls -1tr $DOWNLOADDIR | head -n -10 | xargs -d '\n' rm -f`

would keep the 10 latest files, and delete any more than that.

**Comment by demonbane** [comment]
The current default behavior is to keep downloaded files, so this wouldn't really be extending `AUTODELETE` so much as adding a whole new option. (keep files, but not too many)

With that said, I wouldn't be opposed to adding it, but I'm trying to think of a reason that this **should** be done in plexupdate as opposed to just being a one-liner in your crontab, for example. Do you have a specific use case in mind where this needs to be done as part of plexupdate rather than something you can set up as a separate task?

**Comment by adhawkins** [comment]
Hi,

As you say, it's something I could easily do myself via crontab. However, given that plexupdate gives the option currently to delete the package file when it's been installed, I thought this might be a useful extension of that.

I'll implement it myself via cron for now, and will look out for any future developments.

Andy
