### ISSUE TITLE
Update installation failed

### ISSUE THREAD

**Issue by jaykm** [mrworf/plexupdate#236]
I get the following error on a clean install:

dpkg: unrecoverable fatal error, aborting:
 files list file for package 'iputils-tracepath' is missing final newline
ERROR: Failed to install update. Command 'dpkg -i /tmp/plexmediaserver_1.12.3.4973-215c28d86_amd64.deb' returned error code 2

**Comment by demonbane** [comment]
This is a random dpkg issue that happens when a `.list` file doesn't get written correctly to disk. In this case, it's the one for the `iputils-tracepath` package. You'll see the same error if you try to update any other package as well.

Fortunately, it's a pretty easy fix. If you check `/var/lib/dpkg/info/iputils-tracepath.list` you'll probably see that it either looks like it's blank or has a bunch of junk in it.

<details>
  <summary>Normally it should look similar to this: (click arrow to expand)</summary>

```
/.
/usr
/usr/bin
/usr/bin/tracepath
/usr/bin/traceroute6.iputils
/usr/share
/usr/share/doc
/usr/share/doc/iputils-tracepath
/usr/share/doc/iputils-tracepath/NEWS.Debian.gz
/usr/share/doc/iputils-tracepath/RELNOTES.gz
/usr/share/doc/iputils-tracepath/changelog.Debian.gz
/usr/share/doc/iputils-tracepath/copyright
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/tracepath.8.gz
/usr/share/man/man8/traceroute6.iputils.8.gz
```
</details>
<br/>

The easiest fix is to just delete that file, and then uninstall and reinstall `iputils-tracepath` and it should be fixed.

**Comment by demonbane** [comment]
@jaykm Did this take care of the problem for you?
