### ISSUE TITLE
Updatescript doesnt work with Suse (rpm) package

### ISSUE THREAD

**Issue by sammy2k8** [mrworf/plexupdate#238]
Hey
is the script already prepared for running on rpm based linux systems?. the setup works without any issue, but on the step to recognize the running system and choose the right package to download and install = it always goes for .deb (debian/ubuntu).

is there anything i could do/change to make this nice script working on my opensuse system?
yum is the eq. to dpkg
rpm the eq. to deb

thanks for any help
sammy

**Comment by demonbane** [comment]
I honestly don't think we've ever tested with SUSE. Most of the RPM testing has been on CentOS and Fedora. I'm spinning up an OpenSUSE instance right now, so as long as I can replicate the issue I should be able to have an update pushed out pretty quickly.

**Comment by demonbane** [comment]
Ok, there's a test version that now includes OpenSUSE (and SLES) support. Keep in mind that Plex doesn't officially support SUSE, so if there's a problem with Plex itself we can't help with that, but plexupdate should at least be able to install it for you.

To test out the new version, delete the copy you installed previously (it's under `/opt/plexupdate` by default), and then run the following:
```
BRANCHNAME=opensuse-support bash -c "$(curl -fsSL https://raw.githubusercontent.com/mrworf/plexupdate/opensuse-support/extras/installer.sh)"
```

Let me know how that works for you. If it looks pretty stable I can get it merged into master in the next week or so.

**Comment by demonbane** [comment]
Hmm. For the "failed to start" message, the most likely issue is that your Plex service is named something different. The default name that's used when you install the package they provide is `plexmediaserver.service`.

If you've renamed that systemd service, you can specify the new name in your config file (`/etc/plexupdate.conf`) by providing the name of service in `SYSTEMDUNIT`.

So, for example, if you renamed `plexmediaserver.service` to `plex.service`, you would add a line to your `/etc/plexupdate.conf` that reads:
```
SYSTEMDUNIT="plex.service"
```

As for the invalid group problem, I'm not sure what's happening there. The only place where plexupdate uses chown is to restore permissions to what they were before, so unless you somehow managed to delete the group "plex" while the script was running I can't imagine what could be causing it.

If you can provide the full output of the run so that I can see that error in context that would be helpful.

**Comment by sammy2k8** [comment]
good morning
the thing i could tell is: ive not changed anything (theres no need for doing that) :).
ill check the things provides later and give a short feedback about it.

thank you very much demonbane!

**Comment by sammy2k8** [comment]
hi again
i have found the right key for all - it depends to each other (groups & rights).

the how to to fix the thing for openSuse ist listet here:
https://forums.opensuse.org/content.php/191-Set-up-Plex-Media-Server-in-openSUSE-Tumbleweed-Leap-42-1

Now lets have a look if your updatescript will do its job like on debian systems :smiley:

**Comment by sammy2k8** [comment]
Hey there
im back. so after testing following things should be done for using the plexmediaserver after installing with your script - maybe you want to insert this steps for opensuse users? that would be a very nice thing.

ill take the post from the "opensuse-forum" user "luke2235":

If anyone else is having this problem, I had to take a couple extra steps after installing the fedora rpm. 

1) create plex group in yast and add plex user to the group (as stated above)
2) change ownership of /var/lib/plexmediaserver (sudo chown : plex /var/lib/plexmediaserver)
3) give plex group write permission to this directory (sudo chmod g+w /var/lib/plexmediaserver)
4) then sudo systemctl restart plexmediaserver && sudo systemctl enable plexmediaserver

voila
\\Credits to demonbane, luke2235 & opensuse.org

**Comment by mrworf** [comment]
Putting it in the wiki makes sense, but it should really be reported to https://plex.tv so they can fix the support for openSUSE.

**Comment by mrworf** [comment]
https://github.com/mrworf/plexupdate/wiki/Running-Plex-on-openSUSE

closing this
