### ISSUE TITLE
Can't retrieve the URL needed for download

### ISSUE THREAD

**Issue by bstuparu** [mrworf/plexupdate#261]
Plexupdate can not find the URL anymore. I've tried with no distro specified (it's an Ubuntu machine), with DISTRO set to debian and the results are the same.

However, i've noticed the download link for plex updates changed to https://downloads.plex.tv/plex-media-server-new/1.15.6.1079-78232c603/debian/plexmediaserver_1.15.6.1079-78232c603_amd64.deb

Notice the **-new** in plex-media-server-new and it being **debian** for ubuntu downloads as well.

Could this be the issue?

> root@<machine>:/opt/plexupdate# cat /etc/plexupdate.conf
> AUTOINSTALL='yes'
> PUBLIC='no'
> AUTOUPDATE='yes'
> PLEXSERVER='<machine>'
> PLEXPORT='32400'
> NOTIFY='no'
> TOKEN='<TOKEN>'
> DISTRO='debian'
> BUILD='linux-ubuntu-x86_64'
> DISTRO_INSTALL='dpkg -i'

> root@app02:/opt/plexupdate# ./plexupdate.sh -v --config /etc/plexupdate.conf
> WARNING: You have made changes to the plexupdate files, cannot auto update
> Fetching token from config
> Retrieving list of available distributions
> RELEASE=
> DOWNLOAD=
> CHECKSUM=
> ERROR: Unable to retrieve the URL needed for download (Query DISTRO: debian, BUILD: linux-ubuntu-x86_64)

**Comment by demonbane** [comment]
The reason this is failing is because you have an old `BUILD` line in your configuration. For almost all use cases, you **should not** define `DISTRO`, `BUILD`, or `DISTRO_INSTALL` in your configuration as plexupdate should autodetect those for you. (And if it's not autodetecting them correctly, that's a bug with plexupdate that I'll be happy to fix.) Try removing those lines from your config and running again and let me know if that solves the issue. I'll leave this open until you verify that it's fixed.

**Comment by bstuparu** [comment]
It's apparently fixed now after purging plexupdate completely.
You can close now. Thanks :)
