### ISSUE TITLE
ERROR: Unable to retrieve the URL

### ISSUE THREAD

**Issue by Antimus** [mrworf/plexupdate#273]
When running I get the following error:
ERROR: Unable to retrieve the URL needed for download (Query DISTRO: debian, BUILD: linux-armv7l)

I'm running Plex on a Raspberry Pi

**Comment by demonbane** [comment]
We just recently added support for the Raspberry Pi and right now it's hard-coded to only the Pi 4. I don't know enough about Plex's support for the platform to be able to give you a fix that will definitely work, but if you're willing to do some testing we can potentially expand the support.

If you'd like to force it to download the ARM build and see if it will work on your system, you can edit `/etc/plexupdate.conf` and manually add the following two lines to it:

```
DISTRO='debian'
BUILD='linux-armv7hf_neon'
```

If that works and, more importantly, if the version of Plex it installs for you actually **works**, then send us the output of `cat /proc/cpuinfo` and we can get it added to the code so that it will auto-detect in the future.

**Comment by Antimus** [comment]
I did a manual update using the latest version file: plexmediaserver_1.18.7.2457-77cb9455c_armhf.deb and it worked fine so if that will bring down the same build I'm sure it'll work, I'll wait until I get a notification for a new update, then make this change and run the update manually to be sure, will update when that happens.

for reference, output for cat proc/cpuinfo is:
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a020d3
Serial          : 000000003e467555
Model           : Raspberry Pi 3 Model B Plus Rev 1.3

**Comment by Antimus** [comment]
Don't know if I'm doing something wrong but I made the change, ran the script and got this:

Blah@blah:/opt/plexupdate$ sudo bash plexupdate.sh
Retrieving list of available distributions
Downloading release "plexmediaserver_1.18.8.2527-740d4c206_armhf.deb"
File downloaded
plexupdate.sh: line 492: /tmp/plexmediaserver_1.18.8.2527-740d4c206_armhf.deb: Permission denied
ERROR: Failed to install update. Command ' /tmp/plexmediaserver_1.18.8.2527-740d4c206_armhf.deb' returned error code 126

**Comment by Antimus** [comment]
Still having the same issue, how is the file it's downloading not having the right permissions?

I'm not much of a Linux user so it might be me

**Comment by demonbane** [comment]
This is probably due to the hard-coded reference to the Pi 4 (but not the 3). I'll create a test branch for you to try later tonight.

**Comment by Antimus** [comment]
Thanks

**Comment by demonbane** [comment]
@Antimus Ok, there's a test branch ready to go. First, remove the `DISTRO` and `BUILD` lines from your `plexupdate.conf`. Then run plexupdate using:
```
sudo BRANCHNAME=raspberrypi-test /opt/plexupdate/plexupdate.sh
```

You might see an error at the top about `error: pathspec 'raspberrypi-test'` which is safe to ignore.

**Comment by Antimus** [comment]
Ok something's gone wrong.

I ran that, it downloaded and installed 1.19.xx successfully.

However I can no longer access the Plex server on it's local IP, I can get through plex.tv and the app and it's showing the version as still on 1.18.xxx

**Comment by demonbane** [comment]
Hmm, that sounds like you maybe have two different versions installed, or the service just didn't get restarted properly.
```
sudo systemctl status plexmediaserver
```
should give you something similar to this:
```
● plexmediaserver.service - Plex Media Server
   Loaded: loaded (/lib/systemd/system/plexmediaserver.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/plexmediaserver.service.d
           └─override.conf
   Active: active (running) since Mon 2020-04-20 15:47:25 EDT; 21h ago
  Process: 31925 ExecStartPre=/bin/sh -c /usr/bin/test -d "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" || /bin/mkdir -p "${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR}" (code=exited, status=0/SUCCESS)
 Main PID: 31946 (Plex Media Serv)
    Tasks: 111 (limit: 4915)
   Memory: 614.0M
   CGroup: /system.slice/plexmediaserver.service
           ├─xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
           ├─xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
           └─xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Apr 20 15:47:25 downloader systemd[1]: Starting Plex Media Server...
Apr 20 15:47:25 downloader systemd[1]: Started Plex Media Server.
Apr 20 21:59:47 downloader Plex Media Server[31946]: Connection to xxxx closed by remote host.
Apr 20 22:08:15 downloader Plex Media Server[31946]: Connection to xxxx closed by remote host.
```

What we're most interested in is the "Active" line (the "since" time should be about the time you did the update), and the log output at the end. If the "since" time is from sometime farther back, you can just try manually restarting the service using `sudo systemctl restart plexmediaserver`.

You may also want to take a look at `/tmp/plexinstaller.log` and making sure everything in there looks sane for your setup.

**Comment by Antimus** [comment]
Ok a restart of the service fixed it. Version is up to date, everything
looks good.

**Comment by demonbane** [comment]
@Antimus This fix has been pushed to upstream. Due to a bug you'll just need to reset your local copy of plexupdate to keep updates working normally.  Just run `sudo git reset --hard origin/master` from inside your plexupdate directory before the next time you run plexupdate.

If it's already run and you get a merge error, you can just delete plexupdate completely and re-install it using the instructions from the readme. It will pick up your settings from your existing `plexupdate.conf` so just accept all of the default answers and you should be back to exactly where you were before.

**Comment by demonbane** [comment]
(after you're done also run `sudo git branch` and just make sure that the branch you're on is `master`. The one with the `*` next to it is the branch you're on.)

**Comment by Antimus** [comment]
Sorted, you're a star
