### ISSUE TITLE
it was working before fine....but now

### ISSUE THREAD

**Issue by sSiDs** [mrworf/plexupdate#285]
fatal: unable to access 'https://github.com/mrworf/plexupdate/': Failed sending HTTP2 data

**Comment by demonbane** [comment]
It looks like this might be a [problem with the gnutls version of libcurl](https://superuser.com/questions/1642858/git-throws-fatal-unable-to-access-https-github-com-user-repo-git-failed-se). If you're using curl with libcurl3-gnutls, downgrading libcurl3-gnutls is the suggested fix in that thread. Depending on your distro, you also might be able to upgrade to a newer version of curl, or switch which SSL library is being used.

Because of this I'm assuming that this is not specifically a plexupdate problem, but I'll keep this open until you can confirm that one of the above fixes worked for you. Please let us know once you've had a chance to test.

**Comment by demonbane** [comment]
@sSiDs Were you able to get this resolved?

**Comment by sSiDs** [comment]
it is working now, and updating with plexpass
just see everytime
"WARNING: You have made changes to the plexupdate files, cannot auto update"

**Comment by sSiDs** [comment]
> @sSiDs Were you able to get this resolved?

sid@kino:/$ apt install libcurl3-gnutls
