### ISSUE TITLE
Cron job not running?

### ISSUE THREAD

**Issue by Ashkaan** [mrworf/plexupdate#306]
Here's the install:

```
Found plexupdate.sh in '/opt/plexupdate', using that as your install path

Do you want to install the latest PlexPass releases? (requires PlexPass account) [Y/n] Y

Would you like to automatically install the latest release when it is downloaded? [Y/n] y

When using the auto-install option, would you like to check if the server is in use before upgrading? [Y/n] y
Plex Server IP/DNS name: 127.0.0.1
Plex Server Port: 32400

Writing configuration file '/etc/plexupdate.conf'... done

Would you like to set up automatic daily updates for Plex? [Y/n] y

Do you want to log the daily update runs to syslog so you can examine the output later? [Y/n] y

Should cron send you an email if an update is available/installed? [Y/n] n

Writing configuration file '/etc/plexupdate.cron.conf'... done

Installing daily cron job... done

Configuration complete.
```

After that, it never updates because the cronjob doesn't run.  It never writes a file here:
`/etc/plexupdate.cron.conf`

I found this in /etc/cron.daily, but it never runs:
`plexupdate -> /opt/plexupdate/extras/cronwrapper`

**Comment by demonbane** [comment]
What distro and version are you running?

**Comment by Ashkaan** [comment]
Ubuntu 22 LTS

**Comment by demonbane** [comment]
Hmm, cron should be working by default on your setup, so that shouldn't be a factor. What's more puzzling is that `/etc/plexupdate.cron.conf` doesn't exist. The function that writes the file is the same one that writes out the `Writing configuration file` output from your log above, so if the file didn't get written there should be an error there but there isn't.

The only thing I can think of would be if you're using a strange chroot setup or something maybe? Or if your `/usr/bin/tee` has somehow been modified to not throw an error when it can't write to a file, but both of those are really out there.

Can you double-check to make sure that the file definitely isn't there? To be on the extra safe side, maybe try running:
```
find /etc -name plexupdate.cron.conf -ls
```
And see if it shows it anywhere in there? It's easy enough to manually create that file, but I'd really like to know what's failing before we go down that path since there could be a deeper issue here.

**Comment by Ashkaan** [comment]
Oh boy.. I ran the setup AFTER a reboot and it wrote the file.  I have no idea why it didn't before.  I'll go away now.

**Comment by demonbane** [comment]
No worries, glad you got it working.
