### ISSUE TITLE
broken now with new site layout

### ISSUE THREAD

**Issue by sjorge** [mrworf/plexupdate#58]
The new site layout seems to have broken everything, not really unexpected though.

**Comment by Mawuena** [comment]
Hello,

Thank you @sjorge for posting this.
You beat me to it.

I'm not sure MrWolf will be able to help without information from the Plex team about the new URL.
I've posted something on the Plex Forum about it (https://forums.plex.tv/discussion/222567/plex-media-server-update-automation-download-page-url-change#latest)

So if we can put pressure on them on their side to get an answer, it'd be perfect.
Unless MrWorf have a solution/idea on how to resolve this ?

Sincerely,

Mawuena

**Comment by mrworf** [comment]
Yes, they've made it technically easier, but it's a major change from previously, so it will take me a day or two (especially since today is midsommar celebration in Sweden, which is as big as Thanksgiving in the US if not bigger)

**Comment by Mawuena** [comment]
You rock @mrworf 
Thank you very much !!!!

**Comment by Mawuena** [comment]
And happy midsommar celebration.
Never heard of it but glad I'll sleep a little less dumb tonight :)

**Comment by mrworf** [comment]
@Mawuena @sjorge Pull and try it now, had to move away from RELEASE scheme, but the new setup wiil eventually support ARM and others. Close the issue if it solved your problems.

**Comment by Tommatheussen** [comment]
It sort of works, I was able to install the new version on my Ubuntu 32 bit, I think it can use some tweaks to the DISTRO, BUILD and DISTRO_INSTALL options.

I had to specify DISTRO, BUILD and DISTRO_INSTALL for it too work (since 64 bit is default, and I needed 32 bit).

I tried with a couple options:

- Only BUILD, downloaded 64 bit, so it's ignored

- BUILD and DISTRO, downloaded correct version, but tried to execute sudo /path/to/file (so now dpkg -i)

- 3rd time, with all options specified, that worked.

Anyways, not complaining, just giving the feedback for improvements ;)
Very nice job man, been using your script for quite a while now, never had any real trouble.

Keep it up! :)

**Comment by Mawuena** [comment]
Am at work and will only be able to test it tonight (Fedora 24 Server, 64 bits)
I may be luckier than @Tommatheussen 

However ever since the beginning the line where it says to install it through the "rpm" command had to be changed to "dnf" since the former has been deprecated

Anyway, will give mine (feedback) in few hours
Awesome work @mrworf, really !

**Comment by glberen** [comment]
It works for me now after updating. Ubuntu 14.04. Thank you!

**Comment by sjorge** [comment]
@mrworf looks good now! Using ubuntu 16.04 64-bit

**Comment by grahamrb** [comment]
Also tested on Ubuntu 16.04 64-bit, working great! Thanks for maintaining!

**Comment by Mawuena** [comment]
Confirmed to be working on Fedora 23 Server, 64 Bit !

**Comment by sjorge** [comment]
Seems to be working for everyone, marking as closed

**Comment by mrworf** [comment]
For everyone who followed this thread, latest version posted will autodetect 32/64 bit now and also has an option -l to list possible options. Also improved error messages to avoid confusion. @Tommatheussen

**Comment by Tommatheussen** [comment]
@mrworf Thank you, I just tested it by removing the build, distro and distro_install keys and it worked perfectly :)
