### ISSUE TITLE
systemd timer and service unit

### ISSUE THREAD

**Issue by hakong** [mrworf/plexupdate#63]
Not an issue really, just thought i'd throw in a timer and service unit here. Do what you want with it. People also need to change the path and maybe user depending on how it's run.

/etc/systemd/system/plexupdate.service
```
[Unit]
Description=plexupdate
After=network.target

[Service]
ExecStart=/root/plexupdate/plexupdate.sh -a -c -d -p -s -u
```

/etc/systemd/system/plexupdate.timer
```
[Unit]
Description=Run the plex updater daily

[Timer]
OnCalendar=daily
Persistent=true     
 
[Install]
WantedBy=timers.target
```

```
systemctl daemon-reload
systemctl enable plexupdate.timer
```
Now bring the systemd hate and tell me it's simpler in cron! :laughing: ng:

**Comment by hakong** [comment]
Guess one could use one of systemd's Condition*= to check if plex is in use before running plexupdate.service. Related to #59 .
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#ConditionArchitecture=

**Comment by hakong** [comment]
Updated original comment to include ConditionPathExistsGlob=![...]

**Comment by didyouexpectthat** [comment]
Thanks for posting this. Maybe this would be good in the Wiki or README.md?

**Comment by exetico** [comment]
Hi' 

I trying to test is, but the service returns this:
`yoga@debian:~$ sudo systemctl status plexupdate.service -l
● plexupdate.service - plexupdate
   Loaded: loaded (/etc/systemd/system/plexupdate.service; static)
   Active: failed (Result: exit-code) since Sat 2016-08-06 12:40:02 CEST; 4s ago
  Process: 21482 ExecStart=/root/plexupdate/plexupdate.sh -a -d -p -q (code=exited, status=5)
 Main PID: 21482 (code=exited, status=5)

Aug 06 12:40:02 debian systemd[1]: plexupdate.service: main process exited, code=exited, status=5/NOTINSSTALLED
Aug 06 12:40:02 debian systemd[1]: Unit plexupdate.service entered failed state.
`

Is it, like it should be? The -C option is removed, and i added -q instead.

**Comment by hakong** [comment]
Maybe this will help: https://github.com/mrworf/plexupdate/blob/master/README.md#using-it-from-cron

**Comment by hakong** [comment]
Try plexupdate.sh -a -d -p -c -q

**Comment by hakong** [comment]
Posted in the wiki: https://github.com/mrworf/plexupdate/wiki/Running-plexupdate-daily-as-a-systemd-timer

**Comment by exetico** [comment]
Thanks!
