### ISSUE TITLE
Says its on latest version. Plex says an update exists

### ISSUE THREAD

**Issue by stokbaek** [mrworf/plexupdate#89]
I created the .plexupdate file with my login/passwd for plex.tv but seems like it keeps trying public deb package and not plex pass version.

**Comment by mrworf** [comment]
Did you place the .plexupdate file in the homedirectory of the user you run the script as?

**Comment by stokbaek** [comment]
I have tried in both /root and /home/$USER. Both reports back with this:

```Your OS reports the latest version of Plex (1.0.3.2461-35f0caa) is already installed. Use -f to force download.```

Newest version on plex.tv for plexpass is: ```1.1.0.2611-ba905d2```

**Comment by mrworf** [comment]
And you're using the latest version of plexupdate.sh ? 

Can you share the contents of the .plexupdate file (you can obscure the username/password) ?
Also, if you edited .plexupdate with a windows editor, there is a big risk it used CRLF instead of LF line endings which makes bash not understand what you're saying.

**Comment by stokbaek** [comment]
Seems like it was me being an idiot forgetting that I was running with sudo. Moved the file to ```/root/``` and it all worked

**Comment by mrworf** [comment]
Glad it was resolved :)
